# Copyright 2012-2016 CNRS-UM LIRMM, CNRS-AIST JRL
#
# This file is part of SpaceVecAlg.
#
# SpaceVecAlg is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# SpaceVecAlg is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with SpaceVecAlg.  If not, see <http://www.gnu.org/licenses/>.

version: 1.0.{build}
image: Visual Studio 2015
clone_folder: C:/devel-src/SpaceVecAlg
environment:
  CI_OS_NAME: win32
  CI_TOOL: appveyor
  CHOCO_DEPENDENCIES: "doxygen.portable"
  GIT_DEPENDENCIES: ""
# Should be the same as clone_folder
  PROJECT_SOURCE_DIR: C:/devel-src/SpaceVecAlg
# Do not tinker with the variables below unless you know what you are doing
  SOURCE_FOLDER: C:\devel-src
  CMAKE_INSTALL_PREFIX: C:/devel
  PATH: C:/devel/bin;C:\Libraries\boost_1_67_0\lib64-msvc-14.0;C:\msys64\mingw64\bin;%PATH%
  PKG_CONFIG_PATH: C:/devel/lib/pkgconfig
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14.0
  MINGW_GFORTRAN: C:\msys64\mingw64\bin\gfortran.exe
build_script:
- ps: >-
    . ./.travis/functions.ps1

    setup_build

    ./.travis/dependencies/eigen-3.2.ps1

    install_dependencies

    build_project
test_script:
- cmd: >-
    cd %PROJECT_SOURCE_DIR%/build

    ctest
# This gives access to a remote desktop session after the build finished, useful for debugging
# on_finish:
# - ps: >-
#     reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v UserAuthentication /t REG_DWORD /d 0 /f
# 
#     $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
notifications:
  - provider: Slack
    incoming_webhook:
      secure: gAze73sSl1vrNGaeUEd841yVJ/rVE10tIWjlt+/8OPn0lT42+nSjNqS3bSNgmS+UwyZNe0vzpBTCl6Lx3JEltYNoad96Ss31BEm/7MNLxgc=
