#
# This file was generated by jrl-cmakemodules, do not modify
#

try:
    from setuptools import setup
    from setuptools import Extension
except ImportError:
    from distutils.core import setup
    from distutils.extension import Extension

from Cython.Build import cythonize

import hashlib
import os
import re
import sys

try:
    from numpy import get_include as numpy_get_include
except ImportError:

    def numpy_get_include():
        return ""


win32_build = os.name == "nt"
linux_build = sys.platform.startswith("linux")

sha512 = hashlib.sha512()
src_files = filter(
    len, "@CYTHON_BINDINGS_SOURCES@;@CYTHON_BINDINGS_GENERATE_SOURCES@".split(";")
)


def absolute(src):
    if os.path.isabs(src):
        return src
    else:
        return "{}/{}".format("@CMAKE_CURRENT_SOURCE_DIR@", src)


src_files = map(absolute, src_files)
for f in src_files:
    chunk = 2**12
    with open(f, "r") as fd:
        while True:
            data = fd.read(chunk)
            if data:
                sha512.update(data.encode("ascii"))
            else:
                break
version_hash = sha512.hexdigest()[:7]


def get_lib_name(path):
    ret = os.path.basename(path)
    dot_idx = ret.find(".")
    if dot_idx == -1:
        return ret
    return ret[0:dot_idx]


class pkg_config(object):
    def __init__(self):
        compile_args = "@CYTHON_BINDINGS_COMPILE_DEFINITIONS@"
        self.compile_args = ["-D" + x for x in compile_args.split(";") if len(x)]

        # --- Add NumPy 2.0+ compatibility fallbacks ---
        self.compile_args.append("-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION")
        self.compile_args.append("-DPyDataType_TYPEOBJ(obj)=((PyArray_Descr*)obj)->typeobj")
        self.compile_args.append("-DPyDataType_KIND(obj)=((PyArray_Descr*)obj)->kind")
        # ----------------------------------------------

        self.compile_args = list(set(self.compile_args))
        include_dirs = "@CYTHON_BINDINGS_INCLUDE_DIRECTORIES@"
        include_dirs += ";{}".format(numpy_get_include())
        self.include_dirs = [x for x in include_dirs.split(";") if len(x)]
        self.include_dirs.append("@CMAKE_CURRENT_SOURCE_DIR@/include")
        self.include_dirs = list(set(self.include_dirs))
        library_dirs = "@CYTHON_BINDINGS_LINK_FLAGS@"
        self.library_dirs = [x for x in library_dirs.split(";") if len(x)]
        self.libraries = [
            re.sub("^lib", "", get_lib_name(lib))
            for lib in "@CYTHON_BINDINGS_LIBRARIES@".split(";")
            if len(lib)
        ]
        self.libraries = list(set(self.libraries))
        self.library_dirs += [
            os.path.dirname(lib)
            for lib in "@CYTHON_BINDINGS_TARGET_FILES@".split(";")
            if len(lib)
        ]
        self.library_dirs = list(set(self.library_dirs))
        self.link_args = []
        if linux_build:
            for lib in self.libraries:
                self.link_args += ["-Wl,--no-as-needed", "-l{}".format(lib)]
            self.libraries = []
        if not win32_build:
            self.extra_objects =
