SpaceVecAlg: sva::details Namespace Reference
sva::details Namespace Reference
Functions
template<typename T >
T constexpr sqrtNewtonRaphson (T x, T curr, T prev)
template<typename T >
T constexpr sqrt (T x)
Constexpr version of the square root Return value:
Function Documentation
template<typename T > T constexpr sva::details::sqrt (T x)
Constexpr version of the square root Return value:
For a finite and non-negative value of "x", returns an approximation for the square root of "x"
Otherwise, returns NaN Copied from https://stackoverflow.com/a/34134071
References sqrtNewtonRaphson().
Referenced by sva::sinc(), and sva::sinc_inv().
template<typename T > T constexpr sva::details::sqrtNewtonRaphson (T x, T curr, T prev)
Referenced by sqrt().