Eigen Namespace Reference
Eigen Namespace Reference
Typedefs
template<typename T >
using Vector6 = Matrix< T, 6, 1 >
template<typename T >
using Matrix6 = Matrix< T, 6, 6 >
template<typename T >
using Vector3 = Matrix< T, 3, 1 >
template<typename T >
using Matrix3 = Matrix< T, 3, 3 >
typedef Vector6< double > Vector6d
typedef Matrix6< double > Matrix6d
Functions
template<typename T >
Matrix3< T > vector3ToCrossMatrix (const Vector3< T > &vec)
Convert a 3D vector to a cross product matrix.
template<typename T >
Matrix6< T > vector6ToCrossMatrix (const Vector6< T > &vec)
Convert a 6D vector to a spatial cross product matrix.
template<typename T >
Matrix6< T > vector6ToCrossDualMatrix (const Vector6< T > &vec)
Convert a 6D vector to a spatial dual cross product matrix.
Typedef Documentation
template<typename T > using Eigen::Matrix3 = typedef Matrix<T, 3, 3>
template<typename T > using Eigen::Matrix6 = typedef Matrix<T, 6, 6>
typedef Matrix6<double> Eigen::Matrix6d
template<typename T > using Eigen::Vector3 = typedef Matrix<T, 3, 1>
template<typename T > using Eigen::Vector6 = typedef Matrix<T, 6, 1>
typedef Vector6<double> Eigen::Vector6d
Function Documentation
template<typename T > Matrix3<T> Eigen::vector3ToCrossMatrix (const Vector3< T > & vec) inline
Convert a 3D vector to a cross product matrix.
Referenced by sva::PTransform< T >::dualMatrix(), sva::PTransform< T >::dualMul(), sva::RBInertia< T >::matrix(), sva::PTransform< T >::matrix(), sva::ABInertia< T >::operator+(), and sva::PTransform< T >::transMul().
template<typename T > Matrix6<T> Eigen::vector6ToCrossDualMatrix (const Vector6< T > & vec) inline
Convert a 6D vector to a spatial dual cross product matrix.
template<typename T > Matrix6<T> Eigen::vector6ToCrossMatrix (const Vector6< T > & vec) inline
Convert a 6D vector to a spatial cross product matrix.