SpaceVecAlg: sva::sva_internal Namespace Reference
sva::sva_internal Namespace Reference
Functions
template<typename Derived1 , typename Derived2 , typename Derived3 >
void colwiseCrossEq (const Eigen::MatrixBase< Derived1 > &m1, const Eigen::MatrixBase< Derived2 > &m2, Eigen::MatrixBase< Derived3 > const &result)
template<typename Derived1 , typename Derived2 , typename Derived3 >
void colwiseCrossPlusEq (const Eigen::MatrixBase< Derived1 > &m1, const Eigen::MatrixBase< Derived2 > &m2, Eigen::MatrixBase< Derived3 > const &result)
template<typename Derived1 , typename Derived2 , typename Derived3 >
void colwiseCrossMinusEq (const Eigen::MatrixBase< Derived1 > &m1, const Eigen::MatrixBase< Derived2 > &m2, Eigen::MatrixBase< Derived3 > const &result)
template<typename Derived1 , typename Derived2 , typename Derived3 >
void colwiseLeftMultEq (const Eigen::MatrixBase< Derived1 > &m1, const Eigen::MatrixBase< Derived2 > &m2, Eigen::MatrixBase< Derived3 > const &result)
Function Documentation
colwiseCrossEq()
template<typename Derived1 , typename Derived2 , typename Derived3 > void sva::sva_internal::colwiseCrossEq (const Eigen::MatrixBase< Derived1 > & m1, const Eigen::MatrixBase< Derived2 > & m2, Eigen::MatrixBase< Derived3 > const & result) inline
Referenced by sva::MotionVec< T >::cross(), and sva::MotionVec< T >::crossDual().
colwiseCrossMinusEq()
template<typename Derived1 , typename Derived2 , typename Derived3 > void sva::sva_internal::colwiseCrossMinusEq (const Eigen::MatrixBase< Derived1 > & m1, const Eigen::MatrixBase< Derived2 > & m2, Eigen::MatrixBase< Derived3 > const & result) inline
Referenced by sva::MotionVec< T >::cross(), sva::MotionVec< T >::crossDual(), sva::PTransform< T >::invMul(), sva::RBInertia< T >::mul(), and sva::PTransform< T >::transMul().
colwiseCrossPlusEq()
template<typename Derived1 , typename Derived2 , typename Derived3 > void sva::sva_internal::colwiseCrossPlusEq (const Eigen::MatrixBase< Derived1 > & m1, const Eigen::MatrixBase< Derived2 > & m2, Eigen::MatrixBase< Derived3 > const & result) inline
Referenced by sva::PTransform< T >::dualMul(), sva::RBInertia< T >::mul(), and sva::PTransform< T >::mul().
colwiseLeftMultEq()
template<typename Derived1 , typename Derived2 , typename Derived3 > void sva::sva_internal::colwiseLeftMultEq (const Eigen::MatrixBase< Derived1 > & m1, const Eigen::MatrixBase< Derived2 > & m2, Eigen::MatrixBase< Derived3 > const & result) inline
Referenced by sva::PTransform< T >::dualMul(), and sva::PTransform< T >::mul().