sva::conversions Namespace Reference
sva::conversions Namespace Reference
Convert to and from sva types
Generic functions to convert to/from sva types.
Typedefs
template<typename T >
using affine3_t = Eigen::Transform< T, 3, Eigen::TransformTraits::Affine >
Define an Eigen::Affine3<T>
Functions
template<typename Derived >
PTransform< typename
Derived::Scalar > fromHomogeneous (const Eigen::MatrixBase< Derived > &m, bool rightHandedness=RightHanded)
Convert an homogeneous matrix into a Plucker Transform.
template<typename T >
Eigen::Matrix< T, 4, 4 > toHomogeneous (const PTransform< T > &pt, bool rightHandedness=RightHanded)
Convert a Plucker Transform into an homogeneous matrix.
template<typename T >
PTransform< T > fromAffine (const affine3_t< T > &a, bool rightHandedness=RightHanded)
Convert an Eigen::Affine3<T> into a Plucker Transform.
template<typename T >
affine3_t< T > toAffine (const PTransform< T > &pt, bool rightHandedness=RightHanded)
Convert a Plucker Transform into an Eigen::Affine3<T>
Variables
constexpr bool RightHanded = true
Alias for right handedness (default)
constexpr bool LeftHanded = false
Alias for left handedness.
Detailed Description
Generic functions to convert to/from sva types.
Each function in the conversions namespace allows to convert to and from another type. An important point to note is that sva internally uses a left-handed convention. Hence, all functions will assume that the non-sva objects use a right-handed convention and convert accordingly. This is overridable by the "rightHandedness" argument.
Typedef Documentation
template<typename T > using sva::conversions::affine3_t = typedef Eigen::Transform<T, 3, Eigen::TransformTraits::Affine>
Define an Eigen::Affine3<T>
Function Documentation
template<typename T > PTransform<T> sva::conversions::fromAffine (const affine3_t< T > & a, bool rightHandedness = RightHanded)
Convert an Eigen::Affine3<T> into a Plucker Transform.
Returns
A Plucker Transform of the same type as the input Transform
Parameters
a Input Eigen Transform. Only rotation and translation components are considered.
RightHandedness Handedness of the input Eigen Transform. Defaults to right handedness.
template<typename Derived > PTransform<typename Derived::Scalar> sva::conversions::fromHomogeneous (const Eigen::MatrixBase< Derived > & m, bool rightHandedness = RightHanded)
Convert an homogeneous matrix into a Plucker Transform.
Returns
Plucker Transform equivalent to the input homogeneous matrix
Parameters
m A 4x4 Eigen Matrix
RightHandedness Handedness of the input homogeneous matrix. Defaults to right handedness.
template<typename T > affine3_t<T> sva::conversions::toAffine (const PTransform< T > & pt, bool rightHandedness = RightHanded)
Convert a Plucker Transform into an Eigen::Affine3<T>
Returns
An Eigen::Transform of dimension 3, and same scalar type as the input PTransform.
Parameters
pt Input Plucker Transform.
RightHandedness Handedness of the output Eigen Transform. Defaults to right handedness.
References sva::PTransform< T >::rotation(), and sva::PTransform< T >::translation().
template<typename T > Eigen::Matrix<T, 4, 4> sva::conversions::toHomogeneous (const PTransform< T > & pt, bool rightHandedness = RightHanded)
Convert a Plucker Transform into an homogeneous matrix.
Returns
An Eigen 4x4 homogeneous matrix equivalent to the input Plucker Transform
Parameters
pt Plucker Transform
RightHandedness Handedness of the output homogeneous matrix. Defaults to right handedness.
References sva::PTransform< T >::rotation(), and sva::PTransform< T >::translation().
Variable Documentation
constexpr bool sva::conversions::LeftHanded = false
Alias for left handedness.
constexpr bool sva::conversions::RightHanded = true
Alias for right handedness (default)