SpaceVecAlg: sva::ABInertia< T > Class Template Reference
sva::ABInertia< T > Class Template Reference
Spatial Articulated Body Inertia compact representation.
#include <SpaceVecAlg/ABInertia.h>
Public Types
typedef Vector3< T > vector3_t
typedef Matrix3< T > matrix3_t
typedef Matrix6< T > matrix6_t
Public Member Functions
ABInertia ()
ABInertia (const matrix3_t &M, const matrix3_t &H, const matrix3_t &I)
ABInertia (const TriangularView< matrix3_t, Lower > &ltM, const matrix3_t &H, const TriangularView< matrix3_t, Lower > &ltI)
const matrix3_t & lowerTriangularMassMatrix () const
matrix3_t massMatrix () const
const matrix3_t & gInertia () const
const matrix3_t & lowerTriangularInertia () const
matrix3_t inertia () const
matrix6_t matrix () const
Non compact spatial articulated body inertia matrix.
template<typename T2 >
ABInertia< T2 > cast () const
ABInertia< T > operator+ (const ABInertia< T > &rbI) const
ABInertia< T > operator- (const ABInertia< T > &rbI) const
ABInertia< T > operator- () const
ABInertia< T > & operator+= (const ABInertia< T > &rbI)
ABInertia< T > & operator-= (const ABInertia< T > &rbI)
template<typename T2 >
ABInertia< T > operator* (T2 scalar) const
ABInertia< T > operator+ (const RBInertia< T > &rbI) const
ForceVec< T > operator* (const MotionVec< T > &mv) const
template<typename Derived >
void mul (const Eigen::MatrixBase< Derived > &mv, Eigen::MatrixBase< Derived > &result) const
bool operator== (const ABInertia< T > &abI) const
bool operator!= (const ABInertia< T > &abI) const
Detailed Description
template<typename T>
class sva::ABInertia< T >
Spatial Articulated Body Inertia compact representation.
See Roy Featherstone «Rigid Body Dynamics Algorithms» page 247.
Member Typedef Documentation
matrix3_t
template<typename T> typedef Matrix3<T> sva::ABInertia< T >::matrix3_t
matrix6_t
template<typename T> typedef Matrix6<T> sva::ABInertia< T >::matrix6_t
vector3_t
template<typename T> typedef Vector3<T> sva::ABInertia< T >::vector3_t
Constructor & Destructor Documentation
ABInertia() [1/3]
template<typename T> sva::ABInertia< T >::ABInertia () inline
ABInertia() [2/3]
template<typename T> sva::ABInertia< T >::ABInertia (const matrix3_t & M, const matrix3_t & H, const matrix3_t & I) inline
Parameters
M Mass matrix.
H Generalized inertia matrix.
I Inertia matrix.
ABInertia() [3/3]
template<typename T> sva::ABInertia< T >::ABInertia (const TriangularView< matrix3_t, Lower > & ltM, const matrix3_t & H, const TriangularView< matrix3_t, Lower > & ltI) inline
Parameters
M Lower triangular view of Mass matrix.
H Generalized inertia matrix.
I Lower triangular view Inertia matrix.
Member Function Documentation
cast()
template<typename T> template<typename T2 > ABInertia<T2> sva::ABInertia< T >::cast () const inline
gInertia()
template<typename T> const matrix3_t& sva::ABInertia< T >::gInertia () const inline
Returns
Generalized inertia matrix.
Referenced by sva::PTransform< T >::dualMul(), and sva::PTransform< T >::transMul().
inertia()
template<typename T> matrix3_t sva::ABInertia< T >::inertia () const inline
Returns
Inertia matrix.
Referenced by sva::PTransform< T >::dualMul(), and sva::PTransform< T >::transMul().
lowerTriangularInertia()
template<typename T> const matrix3_t& sva::ABInertia< T >::lowerTriangularInertia () const inline
Returns
Inertia matrix with a zero upper part.
lowerTriangularMassMatrix()
template<typename T> const matrix3_t& sva::ABInertia< T >::lowerTriangularMassMatrix () const inline
Returns
Mass matrix with a zero upper part.
massMatrix()
template<typename T> matrix3_t sva::ABInertia< T >::massMatrix () const inline
Returns
Mass matrix.
Referenced by sva::PTransform< T >::dualMul(), and sva::PTransform< T >::transMul().
matrix()
template<typename T> matrix6_t sva::ABInertia< T >::matrix () const inline
Non compact spatial articulated body inertia matrix.
Referenced by sva::operator<<().
mul()
template<typename T > template<typename Derived > void sva::ABInertia< T >::mul (const Eigen::MatrixBase< Derived > & mv, Eigen::MatrixBase< Derived > & result) const inline
See also
operator*(const MotionVec<T>& mv) const
References sva::forceCouple(), sva::forceForce(), sva::motionAngular(), and sva::motionLinear().
operator!=()
template<typename T> bool sva::ABInertia< T >::operator!= (const ABInertia< T > & abI) const inline
operator*() [1/2]
template<typename T> template<typename T2 > ABInertia<T> sva::ABInertia< T >::operator* (T2 scalar) const inline
References sva::operator*().
operator*() [2/2]
template<typename T > ForceVec< T > sva::ABInertia< T >::operator* (const MotionVec< T > & mv) const inline
Returns
Ia * v
References sva::MotionVec< T >::angular(), and sva::MotionVec< T >::linear().
operator+() [1/2]
template<typename T> ABInertia<T> sva::ABInertia< T >::operator+ (const ABInertia< T > & rbI) const inline
operator+() [2/2]
template<typename T > ABInertia< T > sva::ABInertia< T >::operator+ (const RBInertia< T > & rbI) const inline
Returns
Ia + I
References sva::RBInertia< T >::inertia(), sva::RBInertia< T >::mass(), sva::RBInertia< T >::momentum(), and Eigen::vector3ToCrossMatrix().
operator+=()
template<typename T> ABInertia<T>& sva::ABInertia< T >::operator+= (const ABInertia< T > & rbI) inline
operator-() [1/2]
template<typename T> ABInertia<T> sva::ABInertia< T >::operator- (const ABInertia< T > & rbI) const inline
operator-() [2/2]
template<typename T> ABInertia<T> sva::ABInertia< T >::operator- () const inline
operator-=()
template<typename T> ABInertia<T>& sva::ABInertia< T >::operator-= (const ABInertia< T > & rbI) inline
operator==()
template<typename T> bool sva::ABInertia< T >::operator== (const ABInertia< T > & abI) const inline