name: CI of SpaceVecAlg

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-latest, windows-latest]
        build-type: [Debug, RelWithDebInfo]
        compiler: [gcc, clang]
        exclude:
          # Only default compiler on macos-latest and windows-latest
          - os: macos-latest
            compiler: clang
          - os: windows-latest
            compiler: clang
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install dependencies
      uses: jrl-umi3218/github-actions/install-dependencies@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        ubuntu: |
          apt: cython cython3 python-pytest python3-pytest python-numpy python3-numpy python-coverage python3-coverage python-setuptools python3-setuptools libeigen3-dev doxygen doxygen-latex libboost-all-dev
        macos: |
          brew: eigen boost
          pip: Cython coverage pytest numpy
        windows: |
          pip: Cython coverage pytest numpy
          github:
            - path: eigenteam/eigen-git-mirror
              ref: 3.3.7
        github: |
          - path: jrl-umi3218/Eigen3ToPython
        macos-options: -DPYTHON_BINDING:BOOL=OFF
        windows-options: -DPYTHON_BINDING:BOOL=OFF
    - name: Build and test
      uses: jrl-umi3218/github-actions/build-cmake-project@master
      with:
        compiler: ${{ matrix.compiler }}
        build-type: ${{ matrix.build-type }}
        macos-options: -DPYTHON_BINDING:BOOL=OFF
        windows-options: -DPYTHON_BINDING:BOOL=OFF
    - name: Upload documentation
      # Only run on master branch and for one configuration
      if: matrix.os == 'ubuntu-22.04' && matrix.build-type == 'RelWithDebInfo' && matrix.compiler == 'gcc' && github.ref == 'refs/heads/master'
      run: |
        set -x
        git config --global user.name "JRL/IDH Continuous Integration Tool"
        git config --global user.email "jrl-idh+ci@gmail.com"
        cd $GITHUB_WORKSPACE
        git remote set-url origin "https://gergondet:${{ secrets.GH_PAGES_TOKEN }}@github.com/${{ github.repository}}"
        if `git fetch --depth=1 origin gh-pages:gh-pages`; then
          sudo chown -R `whoami` build/
          cd build/doc && $GITHUB_WORKSPACE/cmake/github/update-doxygen-doc.sh -r $GITHUB_WORKSPACE -b $GITHUB_WORKSPACE/build
        fi
    - name: Slack Notification
      if: failure()
      uses: archive/github-actions-slack@master
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-channel: '#ci'
        slack-text: >
          [SpaceVecAlg] Build *${{ matrix.os }}/${{ matrix.build-type }}* failed on ${{ github.ref }}
